config/routes.rb
Rails.application.routes.draw do
  get 'problem/solve'
  get 'problem/read'
  root 'static_pages#home'
  
  resources :transportations
  resources :demand_sites
  resources :supply_sites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/supply_site.rb
class SupplySite < ApplicationRecord
  has_many :transportation
  has_many :demand_sites, through: :transportation, dependent: :destroy

  validates :capacity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :name, uniqueness: true
end

app/controllers/supply_sites_controller.rb
class SupplySitesController < ApplicationController
  before_action :set_supply_site, only: [:show, :edit, :update, :destroy]

  # GET /supply_sites
  # GET /supply_sites.json
  def index
    @supply_sites = SupplySite.all
  end

  # GET /supply_sites/1
  # GET /supply_sites/1.json
  def show
  end

  # GET /supply_sites/new
  def new
    @supply_site = SupplySite.new
  end

  # GET /supply_sites/1/edit
  def edit
  end

  # POST /supply_sites
  # POST /supply_sites.json
  def create
    @supply_site = SupplySite.new(supply_site_params)

    respond_to do |format|
      if @supply_site.save
        format.html { redirect_to @supply_site, notice: 'Supply site was successfully created.' }
        format.json { render :show, status: :created, location: @supply_site }
      else
        format.html { render :new }
        format.json { render json: @supply_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supply_sites/1
  # PATCH/PUT /supply_sites/1.json
  def update
    respond_to do |format|
      if @supply_site.update(supply_site_params)
        format.html { redirect_to @supply_site, notice: 'Supply site was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply_site }
      else
        format.html { render :edit }
        format.json { render json: @supply_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supply_sites/1
  # DELETE /supply_sites/1.json
  def destroy
    @supply_site.destroy
    respond_to do |format|
      format.html { redirect_to supply_sites_url, notice: 'Supply site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply_site
      @supply_site = SupplySite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_site_params
      params.require(:supply_site).permit(:name, :capacity)
    end
end

app/helpers/supply_sites_helper.rb
module SupplySitesHelper
end

app/views/supply_sites/_form.html.erb
<%= form_with(model: supply_site, local: true) do |form| %>
  <% if supply_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supply_site.errors.count, "error") %> prohibited this supply_site from being saved:</h2>

      <ul>
      <% supply_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/supply_sites/edit.html.erb
<h1>Editing Supply Site</h1>

<%= render 'form', supply_site: @supply_site %>

<%= link_to 'Show', @supply_site %> |
<%= link_to 'Back', supply_sites_path %>

app/views/supply_sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Supply Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supply_sites.each do |supply_site| %>
      <tr>
        <td><%= supply_site.name %></td>
        <td><%= supply_site.capacity %></td>
        <td><%= link_to 'Show', supply_site %></td>
        <td><%= link_to 'Edit', edit_supply_site_path(supply_site) %></td>
        <td><%= link_to 'Destroy', supply_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supply Site', new_supply_site_path %>

app/views/supply_sites/new.html.erb
<h1>New Supply Site</h1>

<%= render 'form', supply_site: @supply_site %>

<%= link_to 'Back', supply_sites_path %>

app/views/supply_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supply_site.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @supply_site.capacity %>
</p>

<%= link_to 'Edit', edit_supply_site_path(@supply_site) %> |
<%= link_to 'Back', supply_sites_path %>