config/routes.rb
Rails.application.routes.draw do
  get 'problem/solve'
  get 'problem/read'
  root 'static_pages#home'
  
  resources :transportations
  resources :demand_sites
  resources :supply_sites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transportation.rb
class Transportation < ApplicationRecord
  belongs_to :supply_site
  belongs_to :demand_site
  
  validates :cost_factor, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  before_action :set_transportation, only: [:show, :edit, :update, :destroy]

  # GET /transportations
  # GET /transportations.json
  def index
    @transportations = Transportation.all
  end

  # GET /transportations/1
  # GET /transportations/1.json
  def show
  end

  # GET /transportations/new
  def new
    @transportation = Transportation.new
  end

  # GET /transportations/1/edit
  def edit
  end

  # POST /transportations
  # POST /transportations.json
  def create
    @transportation = Transportation.new(transportation_params)

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to @transportation, notice: 'Transportation was successfully created.' }
        format.json { render :show, status: :created, location: @transportation }
      else
        format.html { render :new }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transportations/1
  # PATCH/PUT /transportations/1.json
  def update
    respond_to do |format|
      if @transportation.update(transportation_params)
        format.html { redirect_to @transportation, notice: 'Transportation was successfully updated.' }
        format.json { render :show, status: :ok, location: @transportation }
      else
        format.html { render :edit }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportations/1
  # DELETE /transportations/1.json
  def destroy
    @transportation.destroy
    respond_to do |format|
      format.html { redirect_to transportations_url, notice: 'Transportation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transportation
      @transportation = Transportation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transportation_params
      params.require(:transportation).permit(:supply_site_id, :demand_site_id, :cost_factor, :transported_amount)
    end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
  def show_ofv
    if Problem.first.ofv != nil
      `Objective function value: + ` + Problem.first.ofv.to_s
    end
  end
end

app/views/transportations/_form.html.erb
<%= form_with(model: transportation, local: true) do |form| %>
  <% if transportation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transportation.errors.count, "error") %> prohibited this transportation from being saved:</h2>

      <ul>
      <% transportation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supply_site_id %>
    <%= form.collection_select :supply_site_id, SupplySite.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :demand_site_id %>
    <%= form.collection_select :demand_site_id, DemandSite.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :cost_factor %>
    <%= form.text_field :cost_factor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transportations/edit.html.erb
<h1>Editing Transportation</h1>

<%= render 'form', transportation: @transportation %>

<%= link_to 'Show', @transportation %> |
<%= link_to 'Back', transportations_path %>

app/views/transportations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transportations</h1>

<table>
  <thead>
    <tr>
      <th>Supply site</th>
      <th>Demand site</th>
      <th>Cost factor</th>
      <th>Transported amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transportations.each do |transportation| %>
      <tr>
        <td><%= transportation.supply_site.name %></td>
        <td><%= transportation.demand_site.name %></td>
        <td><%= transportation.cost_factor %></td>
        <td><%= transportation.transported_amount %></td>
        <td><%= link_to 'Show', transportation %></td>
        <td><%= link_to 'Edit', edit_transportation_path(transportation) %></td>
        <td><%= link_to 'Destroy', transportation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'New Transportation', new_transportation_path %>

app/views/transportations/new.html.erb
<h1>New Transportation</h1>

<%= render 'form', transportation: @transportation %>

<%= link_to 'Back', transportations_path %>

app/views/transportations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supply site:</strong>
  <%= @transportation.supply_site %>
</p>

<p>
  <strong>Demand site:</strong>
  <%= @transportation.demand_site %>
</p>

<p>
  <strong>Cost factor:</strong>
  <%= @transportation.cost_factor %>
</p>

<p>
  <strong>Transported amount:</strong>
  <%= @transportation.transported_amount %>
</p>

<%= link_to 'Edit', edit_transportation_path(@transportation) %> |
<%= link_to 'Back', transportations_path %>