config/routes.rb
Rails.application.routes.draw do
  get 'problem/solve'
  get 'problem/read'
  root 'static_pages#home'
  
  resources :transportations
  resources :demand_sites
  resources :supply_sites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/demand_site.rb
class DemandSite < ApplicationRecord
  has_many :transportation
  has_many :supply_sites, through: :transportation, dependent: :destroy
  
  validates :demand, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/demand_sites_controller.rb
class DemandSitesController < ApplicationController
  before_action :set_demand_site, only: [:show, :edit, :update, :destroy]

  # GET /demand_sites
  # GET /demand_sites.json
  def index
    @demand_sites = DemandSite.all
  end

  # GET /demand_sites/1
  # GET /demand_sites/1.json
  def show
  end

  # GET /demand_sites/new
  def new
    @demand_site = DemandSite.new
  end

  # GET /demand_sites/1/edit
  def edit
  end

  # POST /demand_sites
  # POST /demand_sites.json
  def create
    @demand_site = DemandSite.new(demand_site_params)

    respond_to do |format|
      if @demand_site.save
        format.html { redirect_to @demand_site, notice: 'Demand site was successfully created.' }
        format.json { render :show, status: :created, location: @demand_site }
      else
        format.html { render :new }
        format.json { render json: @demand_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demand_sites/1
  # PATCH/PUT /demand_sites/1.json
  def update
    respond_to do |format|
      if @demand_site.update(demand_site_params)
        format.html { redirect_to @demand_site, notice: 'Demand site was successfully updated.' }
        format.json { render :show, status: :ok, location: @demand_site }
      else
        format.html { render :edit }
        format.json { render json: @demand_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demand_sites/1
  # DELETE /demand_sites/1.json
  def destroy
    @demand_site.destroy
    respond_to do |format|
      format.html { redirect_to demand_sites_url, notice: 'Demand site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demand_site
      @demand_site = DemandSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demand_site_params
      params.require(:demand_site).permit(:name, :demand)
    end
end

app/helpers/demand_sites_helper.rb
module DemandSitesHelper
end

app/views/demand_sites/_form.html.erb
<%= form_with(model: demand_site, local: true) do |form| %>
  <% if demand_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(demand_site.errors.count, "error") %> prohibited this demand_site from being saved:</h2>

      <ul>
      <% demand_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :demand %>
    <%= form.text_field :demand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/demand_sites/edit.html.erb
<h1>Editing Demand Site</h1>

<%= render 'form', demand_site: @demand_site %>

<%= link_to 'Show', @demand_site %> |
<%= link_to 'Back', demand_sites_path %>

app/views/demand_sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Demand Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Demand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demand_sites.each do |demand_site| %>
      <tr>
        <td><%= demand_site.name %></td>
        <td><%= demand_site.demand %></td>
        <td><%= link_to 'Show', demand_site %></td>
        <td><%= link_to 'Edit', edit_demand_site_path(demand_site) %></td>
        <td><%= link_to 'Destroy', demand_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demand Site', new_demand_site_path %>

app/views/demand_sites/new.html.erb
<h1>New Demand Site</h1>

<%= render 'form', demand_site: @demand_site %>

<%= link_to 'Back', demand_sites_path %>

app/views/demand_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demand_site.name %>
</p>

<p>
  <strong>Demand:</strong>
  <%= @demand_site.demand %>
</p>

<%= link_to 'Edit', edit_demand_site_path(@demand_site) %> |
<%= link_to 'Back', demand_sites_path %>